name: transcript-app
services:
- environment_slug: python
  github:
    branch: main
    repo: SyneosAndreia/Transcript
  source_dir: backend
  run_command: gunicorn app:app
  build_command: pip install -r requirements.txt