name: transcript-app
services:
- environment_slug: python
  github:
    branch: main
    repo: SyneosAndreia/Transcript
  source_dir: backend
  run_command: gunicorn --bind 0.0.0.0:$PORT --workers 3 app:app
  build_command: pip install -r requirements.txt
  envs:
    - key: FLASK_ENV
      value: production
      type: SHARED